### ISSUE TITLE
smart_listing_controls_for auto-fires once (and only once)

### ISSUE THREAD

**Issue by davidrouten** [Sology/smart_listing#68]
Let me start off by saying that I LOVE smart_listing and how easy it makes simple sorting and filtering through AJAX. Thanks for all the hard work and I hope I'll be able to contribute in some small way! The issue is as follows:

Sorting, filtering, etc. all are working perfectly. The issue I'm having is that when using smart_listing_controls_for with a select box (or a text box), when the input is changed, it will auto-fire and update the table with the correct filtered results. However, it only ever works the first time. On any page. Using a button to submit works as predicted, but I'd really like to ditch the button and just have it always fire on change. Checking the logs, the first change fires off the GET request as it should, but any subsequent changes do nothing. My first guess would be that it is losing it's binding somewhere along the line?

What information does anyone need from me to help fix this issue? I'm not using `turbolinks` in this project nor am I using `bootstrap-daterangepicker-rails`.

Thanks in advance, -D

**Comment by MindRave** [comment]
Hey everyone!

Same here. Disabling Turbolinks didn't work. Going through "application.js" and deleting "requires" one by one didn't help either - same story.

Some of my code:

**controller:**
    users_scope = User.where('id <> ?', current_user.id)
    users_scope = users_scope.where('name LIKE :filter', filter: "%#{params[:filter]}%") if params[:filter]
    @activity = Activity.find(params[:id])
    @users = smart_listing_create :users, users_scope, partial: "activities/user_list", default_sort: { name: "asc" }

**_user_list:**

    <%= smart_listing_controls_for(:users, { class: "form-inline" }) do %>
      <div class="filter input-append">
        <%= text_field_tag :filter, '', class: "filter-users form-control", placeholder: "Filtrer users", autocomplete: :off %>
      </div>
      <button type="submit" class="btn btn-primary disabled">Filtrer</button>
    <% end %>
    <% smart_listing.collection.each do |user| %>
      <%= render 'users/user', user: user %>
    <% end %>

Sometimes it behaves weirdly, reloading the whole page when I type one letter. I'm sure it's something on my end, but can't figure out what exactly.

The above setup works when I type a query, e.g "Mike" and hit "Enter". But auto-refreshing doesn't work. Also, the above code generates a data-smart-listing="users", when the one on your example website is data-smart-listing="controls" (while we have mostly the exact same setup). If I write the form by hand, with data-smart-listing="controls", the auto-refresh happens every time I stop typing (as it should) - but I get "smart_listing.params is not a function" in the console, and no refresh whatsoever.

P.S: I'd love to be able to use that "like" scope you have used, but I defined mine because "like", of course, doesn't work.

**Comment by SixiS** [comment]
+1 Looks like the search box loses its "on change" binding when it loads in the new content via ajax.

A workaround is to do the on change binding yourself to work after the content loads back in.

```javascript
$(function () {
  $('body').on('change', '.smart-listing-controls input', function(e){
    e.preventDefault();
    $(this).closest('form').submit();
  });
});
```
Smart listing generates a remote form around your fields when you do `smart_listing_controls_for` which normally submits on change.
So the code just submits that form on change but the binding is attached to body so it doesn't break after the content reloads.

You can add any other events you would like - i.e. add events for click on the submit button in the control group form if you need.

I have a bit of a dig through the smart_listing JS to see where the change is triggered but couldn't find it...

**Comment by davidrouten** [comment]
I solved it thanks to @MindRave and @SixiS!! You need to take the filter (i.e. `<%= smart_listing_controls_for... do %>`) out of the partial you are rendering (`_user_list.html.erb` for @MindRave), and just place it in the file--index.html.erb I'm assuming--that contains the `<%= smart_listing_render :users %>` code. If the code is inside the partial, it will be re-rendered every time you search and will NOT re-bind the auto-fire AJAX submit on the filter. Once you take it out of said partial, voila, auto-refresh works every time. Hope this helps and thanks to both of you for helping me figure out what exactly was causing it and fixing this problem site-wide.

-Dave

**Comment by MindRave** [comment]
@davidrouten, @SixiS confirming that the solution proposed by @davidrouten works!
Thank you so much for your help!
