### ISSUE TITLE
Using Rspec test view with Smart Listing

### ISSUE THREAD

**Issue by XjulI1** [Sology/smart_listing#75]
Hello,

I have a problem with my Rspec View tests and Smart Listing. How can I used the gem to mock/use the function "smart_listing_render" ? Because when I launch my tests, Rspec does not recognize the function.

ActionView::Template::Error: undefined method `smart_listing_render' for #<#<Class:0x007f96702a8b50>:0x007f96702802e0>
./app/views/backoffice/dossiers/index.html.haml:4:in `_app_views_backoffice_dossiers_index_html_haml__2296039462971417529_70142073117820'
./spec/views/backoffice/dossiers/index_html.haml_spec.rb:66:in `block (3 levels) in <top (required)>'
-e:1:in `<main>'

Thanks

**Comment by ljachymczyk** [comment]
I think you should use feature specs with i.e. Capybara to test smart listing.

**Comment by fanjieqi** [comment]
I have the same problem.

Firstly, I add the inclusion of SmartListing directly:

```ruby
require 'rails_helper'

RSpec.describe "callings/index", type: :view do
  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper

  before(:each) do
    smart_listing_create(:callings, Calling.includes(:user, :partition), partial: "callings/listing")
  end

  it "renders a list of callings" do
    render
  end
end
```

Then, the problem would be
```
NoMethodError:
   undefined method `smart_listing_config_profile' for #<#<Class:0x00007fce0f4d2080>:0x00007fce100736c8>
      
   # /Users/fanjieqi/.rvm/gems/ruby-2.3.6/gems/smart_listing-1.2.1/app/helpers/smart_listing/helper.rb:15:in `smart_listing_create'
   # ./spec/views/callings/index.html.haml_spec.rb:8:in `block (2 levels) in <top (required)>'
```
It's at [helper.rb:15](https://github.com/Sology/smart_listing/blob/master/app/helpers/smart_listing/helper.rb#L15).
Because the controller in Rspec views is **ActionView::TestCase::TestController**, whose view_context doesn't have the method smart_listing_config_profile.

So, I try to add a monkey patch in my rails_helper.rb, by using view_context.**try**(:smart_listing_config_profile).
```ruby
module SmartListing::Helper::ControllerExtensions
  def smart_listing_create *args
    options = args.extract_options!
    name = (args[0] || options[:name] || controller_name).to_sym
    collection = args[1] || options[:collection] || smart_listing_collection

    view_context = self.respond_to?(:controller) ? controller.view_context : self.view_context
    options = {:config_profile => view_context.try(:smart_listing_config_profile) }.merge(options)

    list = SmartListing::Base.new(name, collection, options)
    list.setup(params, cookies)

    @smart_listings ||= {}
    @smart_listings[name] = list

    list.collection
  end
end
```

It works for me, but I really wonder Is there any better solution?
